problems=["Single Number",
"Maximum Depth of Binary Tree",
"Same Tree",
"Reverse Integer",
"Best Time to Buy and Sell Stock II",
"Unique Binary Search Trees",
"Linked List Cycle",
"Binary Tree Preorder Traversal",
"Binary Tree Inorder Traversal",
"Populating Next Right Pointers in Each Node",
"Search Insert Position",
"Remove Duplicates from Sorted List",
"Single Number II",
"Roman to Integer",
"Climbing Stairs",
"Maximum Subarray",
"Integer to Roman",
"Merge Two Sorted Lists",
"Remove Element",
"N-Queens II",
"Convert Sorted Array to Binary Search Tree",
"Swap Nodes in Pairs",
"Balanced Binary Tree",
"Remove Duplicates from Sorted Array",
"Symmetric Tree",
"Merge Sorted Array",
"Gray Code",
"Pascal's Triangle",
"Sort Colors",
"Plus One",
"Generate Parentheses",
"Best Time to Buy and Sell Stock",
"Rotate Image",
"Binary Tree Level Order Traversal II",
"Unique Paths",
"Permutations",
"Minimum Path Sum",
"Binary Tree Postorder Traversal",
"Container With Most Water",
"Search a 2D Matrix",
"Linked List Cycle II",
"Binary Tree Level Order Traversal",
"Search in Rotated Sorted Array II",
"Spiral Matrix II",
"Set Matrix Zeroes",
"Remove Duplicates from Sorted Array II",
"Pascal's Triangle II",
"Path Sum",
"Combinations",
"Populating Next Right Pointers in Each Node II",
"Remove Nth Node From End of List",
"Sum Root to Leaf Numbers",
"Minimum Depth of Binary Tree",
"Palindrome Number",
"Length of Last Word",
"Search in Rotated Sorted Array",
"Trapping Rain Water",
"Valid Parentheses",
"Unique Paths II",
"Valid Sudoku",
"Longest Consecutive Sequence",
"Flatten Binary Tree to Linked List",
"Subsets",
"Path Sum II",
"Longest Common Prefix",
"Jump Game",
"Search for a Range",
"3Sum Closest",
"Convert Sorted List to Binary Search Tree",
"Unique Binary Search Trees II",
"Count and Say",
"Triangle",
"Subsets II",
"Binary Tree Zigzag Level Order Traversal",
"Combination Sum",
"Partition List",
"Construct Binary Tree from Inorder and Postorder Traversal",
"Construct Binary Tree from Preorder and Inorder Traversal",
"Pow(x, n)",
"Reverse Linked List II",
"Letter Combinations of a Phone Number",
"Palindrome Partitioning",
"N-Queens",
"Add Binary",
"Validate Binary Search Tree",
"Next Permutation",
"Edit Distance",
"Reverse Nodes in k-Group",
"Insertion Sort List",
"Remove Duplicates from Sorted List II",
"Permutations II",
"Gas Station",
"Distinct Subsequences",
"Combination Sum II",
"Jump Game II",
"ZigZag Conversion",
"Anagrams",
"Recover Binary Search Tree",
"Copy List with Random Pointer",
"Add Two Numbers",
"Merge k Sorted Lists",
"Valid Palindrome",
"First Missing Positive",
"Longest Substring Without Repeating Characters",
"Scramble String",
"Best Time to Buy and Sell Stock III",
"Clone Graph",
"Sqrt(x)",
"Rotate List",
"Permutation Sequence",
"Maximal Rectangle",
"Implement strStr()",
"4Sum",
"Largest Rectangle in Histogram",
"Sudoku Solver",
"Longest Palindromic Substring",
"Word Break",
"Merge Intervals",
"Spiral Matrix",
"Multiply Strings",
"Restore IP Addresses",
"Sort List",
"Insert Interval",
"Reorder List",
"Evaluate Reverse Polish Notation",
"Regular Expression Matching",
"Binary Tree Maximum Path Sum",
"Word Search",
"Simplify Path",
"Longest Valid Parentheses",
"Interleaving String",
"Two Sum",
"Candy",
"Word Ladder",
"Palindrome Partitioning II",
"Substring with Concatenation of All Words",
"Minimum Window Substring",
"Median of Two Sorted Arrays",
"3Sum",
"Divide Two Integers",
"Decode Ways",
"Word Break II",
"String to Integer (atoi)",
"Text Justification",
"Reverse Words in a String",
"Surrounded Regions",
"LRU Cache",
"Wildcard Matching",
"Word Ladder II",
"Valid Number",
"Max Points on a Line",]

N=4

import random

def main():
	random.shuffle(problems)
	for p in problems[0:N]:
		print(p)

if __name__ == '__main__':
	main()